### PR TITLE
terminate synthesis on illegla clk connection

### PR DESCRIPTION
**Pull request by awaisabbas006**

### CODE REVIEW

**Comment by awaisabbas006** [comment]
Hi @thierryBesson @ayyazahmed-rs can you please review the PR

**Comment by alaindargelas** [comment]
@awaisabbas006 did you run "make test/batch_all" ? Did it pass?

**Comment by awaisabbas006** [comment]
Hi @alaindargelas yes it is passing

**Comment by alaindargelas** [comment]
@awaisabbas006 please cleanup your warnings always:
src/synth_rapidsilicon.cc:3714:22: warning: unused variable ‘has_clk’ [-Wunused-variable]
 3714 |                 bool has_clk = false;
      |                      ^~~~~~~

**Pull request merged**
