### PR TITLE
New SEC check Pass for stage wise equivalence checking

### PR DESCRIPTION
**Pull request by AYYAZmayo**

### CODE REVIEW

**Comment by alaindargelas** [comment]
@AYYAZmayo did you run "make test/batch_all", did it pass?

**Comment by alaindargelas** [comment]
@AYYAZmayo @awaisabbas006 @thierryBesson any update here?

**Comment by BessonThierry** [comment]
@alaindargelas we need a team review next Thursday to decide if we commit or still improve the current development.

**Comment by BessonThierry** [comment]
@AYYAZmayo please can you test your current code ('make test/batch_all') and we can merge it if everything is fine. Thanks.

**Comment by AYYAZmayo** [comment]
> @AYYAZmayo please can you test your current code ('make test/batch_all') and we can merge it if everything is fine. Thanks.

@BessonThierry , ok Sure.

**Comment by ayyazahmed-rs** [comment]
Under (**make test/batch_all**) following tests are clear.
 test/batch  test/batch_gen2  solver/tests

**Review by BessonThierry — APPROVED** [review]

**Comment by alaindargelas** [comment]
@ayyazahmed-rs please submit a PR in yosys_verific_rs

**Pull request merged**
