### PR TITLE
Add error message for illegal port connection to fix EDA-2834

### PR DESCRIPTION
**Pull request by awaisabbas006**

### CODE REVIEW

**Comment by awaisabbas006** [comment]
@thierryBesson I have created a PR to add error message for illegal port connection, if an input port is connected to both I_BUF and other components, please review the PR.

**Review by BessonThierry — COMMENTED** [review]
@awaisabbas006 I see two times "design -save original" and splitnets both called when entering in 'get_port_cell_relation' and then after calling 'get_port_cell_relation'. 
Are the ones after calling 'get_port_cell_relation' necessary ? especially also because they change the netlist and the object on which 'get_port_cell_relation' built the 'in_2_cell' dictionnary ?

**Comment by BessonThierry** [comment]
@awaisabbas006 theoritically a second call to "splitnet" should do nothing since everything has been already splitted. And the "design save original " should be done at the same level as the "design -load original" (not one in the fucntion and the other one outside the function).

**Comment by awaisabbas006** [comment]
@thierryBesson please review now, I indeed had one mistake in my previous commit, i.e., I did not load  the original design before leaving the get_port_cell_relation() function. I now use only one splitnet call.

**Review by BessonThierry — COMMENTED** [review]
it looks ok to me, Thanks.

**Review by BessonThierry — APPROVED** [review]
it looks ok to me, Thanks.

**Pull request merged**
